server:
  port: 8085   #  配置启动端口号

spring: #springboot的配置
  banner:
    location: classpath:banner.txt
  profiles:
    include: undertow, swagger  # 引用其他的yml文件
  threads:
    virtual:
      enabled: true  # 开启虚拟线程

  servlet:
    multipart:
      max-file-size: 10MB
  datasource: #定义数据源
    #127.0.0.1为本机测试的ip，3306是mysql的端口号。serverTimezone是定义时区，照抄就好，mysql高版本需要定义这些东西
    #useSSL也是某些高版本mysql需要问有没有用SSL连接
    url: jdbc:mysql://localhost:3306/im-core?useSSL=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true # MySQL Connector/J 8.X 连接的示例
    username: root # 数据库账号
    password: 19940806 # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库新的驱动，下面连接url一定要加区时
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    publisher-returns: true #设置publisher-returns消息成功则会向发布者发送成功，失败时不会将消息丢弃，而是返回给发布者，发布者根据需求处理
    publisher-confirm-type: correlated #开启发布确认模式，具体有三个值，具体的可以去百度


  data:
    redis:
      host: localhost
      port: 6379
      password:
      username:
      database: 0      # 数据库索引（默认为0）
      timeout: 1800000 # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 20  # 连接池最大连接数
          max-wait: -1    # 最大阻塞等待时间（负数表示无限制）
          max-idle: 5     # 最大空闲连接数
          min-idle: 0     # 最小空闲连接数


# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:/mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印sql
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl


minio:
  endpoint: http://127.0.0.1:9000 #内网地址
  public: http://127.0.0.1:9000  #外网访问地址
  #public: http://dns.kizhou.cn:11144  #外网访问地址
  accesskey: minioadmin
  secretkey: minioadmin
  bucketName: box-im


# TODO: log settings
logging:
  config: classpath:logback-plus.xml  #日志配置文件，会在当前项目下去找日志配置文件
  level:
    com.xy.*.mapper: debug
    com.xy.*: debug
    org.springframework: warn