#springdoc相关配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'server'
      paths-to-match: '/**'
      packages-to-scan: com.xy.server  #改成你自己的包名，一般到启动类的包名



# TODO: knife4j相关配置 可以不用改
knife4j:
  enable: true        # 开启增强配置
  production: false   # 开启生产环境屏蔽
  setting:
    language: zh_cn   # 默认中文
    swagger-model-name: 实体类
