server:
    port: 8081   #  配置启动端口号
    compression:
        enabled: true #  开启gzip压缩
        mime-types: application/json,application/xml,text/html,text/xml,text/plain
        min-response-size: 1024

spring:
    banner:
        location: classpath:banner.txt
    profiles:
        include: undertow  # 引用其他的yml文件
    threads:
        virtual:
            enabled: true  # 开启虚拟线程
    ai:
        openai:
            api-key: "sk-0b48339cb3bd49f58bab98d972e180ee" # 安全起见，从系统环境变量读取
            base-url: https://api.deepseek.com
            chat:
                options:
                    model: deepseek-chat
                    temperature: 0.5
